In [2]:
import numpy as np
n1=np.array([1,2,3,4])
n1

array([1, 2, 3, 4])

In [5]:
n2=np.array([[1,2,3,4],[5,6,7,8]])
print(n2)

[[1 2 3 4]
 [5 6 7 8]]


Initializing Numpy with Zeros

In [6]:
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [7]:
import numpy as np
n2=np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
n3=np.full((2,10),3)
n3

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

using a range method  

In [13]:
n4= np.arange(9,91,9)

In [14]:
n4

array([ 9, 18, 27, 36, 45, 54, 63, 72, 81, 90])

initializing numpy array with random numbers

In [5]:
n5=np.random.randint(90,101,5)
n5

array([ 95,  96, 100,  99,  91])

Finding the shape of the array

In [16]:
n6=np.array([[1,2,3],[4,5,6]])
n6

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
n6.shape

(2, 3)

In [18]:
n6.shape=(3,2)
n6


array([[1, 2],
       [3, 4],
       [5, 6]])

lets learn how stacks works in numpy 

In [19]:
n1= np.array([1,2,3])
n2=np.array([4,5,6])

In [21]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [23]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

Intersection in array

In [24]:
n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,7,8,9])

In [25]:
np.intersect1d(n1,n2)

array([5, 6])

In [26]:
np.setdiff1d(n1,n2)

array([1, 2, 3, 4])

In [28]:
np.setdiff1d(n2,n1)

array([7, 8, 9])

simple mathemetical in numpy arrays

In [29]:
n1=np.array([10,20])
n2=np.array([30,40])

In [31]:
np.sum([n1,n2])

100

In [32]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [33]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [40]:
n1=np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [35]:
n1=n1+2

In [36]:
n1

array([12, 22, 32, 42, 52])

In [37]:
n1-2

array([10, 20, 30, 40, 50])

In [38]:
n1*2

array([ 24,  44,  64,  84, 104])

In [39]:
n1/1

array([12., 22., 32., 42., 52.])

In [41]:
np.mean(n1)

30.0

In [42]:
np.median(n1)

30.0

In [43]:
np.std(n1)

14.142135623730951

lets learn some numpy matrix

In [55]:
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
n1[0]

array([1, 2, 3])

In [47]:
n1[1]

array([4, 5, 6])

In [50]:
n1[2]

array([7, 8, 9])

In [51]:
n1[:,0]

array([1, 4, 7])

In [52]:
n1[:,1]

array([2, 5, 8])

In [53]:
n1[:,2]

array([3, 6, 9])

In [56]:
np.transpose(n1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [57]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
n2=np.array([[9,8,7],[6,5,4],[3,2,1]])
n2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [59]:
n1.dot(n2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [60]:
n2.dot(n1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [61]:
n1=np.save('numpy_np',n1)


In [62]:
n2=np.load('numpy_np.npy')

In [63]:
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])